import { createFileRoute } from "@tanstack/react-router";

// Public callback endpoint. ZarinPal redirects the customer's browser here
// via GET (or POST on some flows) with ?Authority=...&Status=OK|NOK.
//
// Security notes:
//   - The Authority is opaque and generated by ZarinPal; we verify with the
//     provider before creating the booking (never trust ?Status alone).
//   - Amount used for verification comes from our stored intent, NOT from
//     any client-supplied value.
//   - The intent row is single-use: after a terminal transition (verified
//     or failed) we ignore further callbacks for the same authority.

function redirect(location: string) {
  return new Response(null, { status: 303, headers: { Location: location } });
}

async function handle(request: Request): Promise<Response> {
  const url = new URL(request.url);
  const authority =
    url.searchParams.get("Authority") || url.searchParams.get("authority") || "";
  const status =
    url.searchParams.get("Status") || url.searchParams.get("status") || "";

  if (!authority) return redirect("/payment/failed?reason=missing_authority");

  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

  const { data: intent, error: intentErr } = await supabaseAdmin
    .from("payment_intents")
    .select("*")
    .eq("provider", "zarinpal")
    .eq("authority", authority)
    .maybeSingle();

  if (intentErr || !intent) {
    return redirect("/payment/failed?reason=unknown_authority");
  }

  // If already terminal, redirect to the appropriate destination without re-verifying.
  if (intent.status === "verified" && intent.booking_id) {
    const { signBookingId } = await import("@/lib/booking-token.server");
    const t = signBookingId(intent.booking_id as string);
    return redirect(`/booking/${intent.booking_id}?t=${encodeURIComponent(t)}`);
  }
  if (intent.status === "failed" || intent.status === "cancelled") {
    return redirect(`/payment/failed?reason=${intent.status}`);
  }

  // User cancelled at gateway.
  if (status.toUpperCase() !== "OK") {
    await supabaseAdmin
      .from("payment_intents")
      .update({ status: "cancelled", error_code: "user_cancelled" })
      .eq("id", intent.id);
    return redirect("/payment/failed?reason=cancelled");
  }

  const { zpVerify } = await import("@/lib/zarinpal.server");
  const verified = await zpVerify(authority, intent.amount_toman);
  if (!verified.ok) {
    await supabaseAdmin
      .from("payment_intents")
      .update({ status: "failed", error_code: String(verified.code) })
      .eq("id", intent.id);
    console.error("[zarinpal] verify failed", verified);
    return redirect(`/payment/failed?reason=verify_${verified.code}`);
  }

  // Payment verified. Create the booking now.
  const payload = intent.booking_payload as {
    name: string;
    phone: string;
    consoleType: string;
    packageType: string;
    startDate: string;
    endDate: string;
    notes?: string;
  };

  const { data: newId, error: rpcErr } = await supabaseAdmin.rpc("create_booking", {
    _name: payload.name,
    _phone: payload.phone,
    _console_type: payload.consoleType,
    _package_type: payload.packageType,
    _start_date: payload.startDate,
    _end_date: payload.endDate,
    _notes: payload.notes ?? undefined,
  });

  if (rpcErr || !newId) {
    // Payment succeeded but booking failed — mark intent so ops can refund.
    await supabaseAdmin
      .from("payment_intents")
      .update({
        status: "failed",
        ref_id: verified.refId,
        error_code: rpcErr?.code || "booking_create_failed",
      })
      .eq("id", intent.id);
    console.error("[zarinpal] booking creation failed after payment", rpcErr);
    return redirect(`/payment/failed?reason=booking_create_failed&ref=${verified.refId}`);
  }

  const bookingId = newId as string;
  await supabaseAdmin
    .from("payment_intents")
    .update({ status: "verified", ref_id: verified.refId, booking_id: bookingId })
    .eq("id", intent.id);

  const { signBookingId } = await import("@/lib/booking-token.server");
  const token = signBookingId(bookingId);
  return redirect(`/booking/${bookingId}?t=${encodeURIComponent(token)}`);
}

export const Route = createFileRoute("/api/public/payments/zarinpal/callback")({
  server: {
    handlers: {
      GET: ({ request }) => handle(request),
      POST: ({ request }) => handle(request),
    },
  },
});